uav_model:
    default:
        vehicle_mass: 1.0
        vehicle_inertia_xx: 0.0049
        vehicle_inertia_yy: 0.0049
        vehicle_inertia_zz: 0.0049
    STM32:
        vehicle_mass: 0.671
        vehicle_inertia_xx: 0.00255
        vehicle_inertia_yy: 0.00277
        vehicle_inertia_zz: 0.00542
    CFB:
        vehicle_mass: 0.609
        vehicle_inertia_xx: 0.00264
        vehicle_inertia_yy: 0.00272
        vehicle_inertia_zz: 0.00487
    JFR:
        vehicle_mass: 0.917
        vehicle_inertia_xx: 0.00363
        vehicle_inertia_yy: 0.0040
        vehicle_inertia_zz: 0.0060
    STMCFB:
        vehicle_mass: 0.771
        vehicle_inertia_xx: 0.004
        vehicle_inertia_yy: 0.004
        vehicle_inertia_zz: 0.006

motor_model:
    motor_inertia: 6.62e-6
    max_prop_speed: 2750.0
    min_prop_speed: 0.0
    moment_arm: 0.08
    motor_time_constant: 0.02
    # thrust_coefficient: 1.91e-6
    thrust_coefficient: 1.6201e-6
    # torque_coefficient: 2.6e-7
    torque_coefficient: 1.7762e-8
    drag_coefficient: 0.1
    angular_process_noise: 1.25e-7
    linear_process_noise: 0.0005
    reset_timeout: 0.1
    min_arming_thrust: 9.9

imu_model:
    accelerometer_variance: 0.005
    gyroscope_variance: 0.003

simulation:
    init_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
    gravity: 9.81

controller:
    PID:
        posPID:
            P: 4.8
            I: 0.0
            D: 2.9
        posvertPID:
            P: 8.4
            I: 0.01
            D: 3.1
    NDI:
        safety:
            maxAttAngle: 1.4
            maxAttIncrement: 0.55
            maxThrustIncrement: 3.0
            maxVelPosFatal: 210.0
            maxAccFatal: 25.0
        posPID:
            P: 3.0
            I: 0.0
            D: 0.3
        velPID:
            P: 6.0
            I: 0.0
            D: 0.5
        posvertPID:
            P: 3.0
            I: 0.0
            D: 0.3
        velvertPID:
            P: 4.5
            I: 0.0
            D: 0.3
        intGain:
            phi: 0.0
            theta: 0.0
            psi: 0.0
        propGain:
            phi: 90.0
            theta: 90.0
            psi: 16.41
        # use with theoretical control effectiveness
        derGain:
            phi: 10.0
            theta: 10.0
            psi: 14.0
        # use with pengus control effectiveness
    #     derGain:
    #         phi: 8.5
    #         theta: 8.5
    #         psi: 14.
    #     accFilter:
    #         # cutoff at 10 Hz
    #         gainP: 3947.84176043574
    #         gainQ: 88.8576587631673
    #     accFilter:
    #         # cutoff at 14 Hz
    #         gainP: 7737.76985045406
    #         gainQ: 124.400722268434
    #     accFilter:
    #         # cutoff at 20 Hz
    #         gainP: 15791.367041743
    #         gainQ: 177.715317526335
    #     accFilter:
    #         # cutoff at 25 Hz
    #         gainP: 24674.0110027234
    #         gainQ: 222.144146907918
        accFilter:
            # cutoff at 30 Hz
            gainP: 35530.5758439217
            gainQ: 266.572976289502